name: "Apply Stack after PR is Merged"

on:
  push:
    branches:
      - main
    paths:
      - "modules/storage/terraform-aws-ebs/**"
      - "./github/workflows/storage/terraform-aws-ebs.yaml"

permissions:
  contents: read
  pull-requests: write
  issues: read

jobs:
  terraform:
    name: "Terraform CDK Deploy"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/storage/terraform-aws-ebs
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install

      - name: Generate module and provider bindings
        run: npx cdktf-cli get

      # Remove this step if you don't have any
      #- name: Run unit tests
      #  run: yarn test

      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v0.1.0
        with:
          terraformVersion: 1.3.0
          workingDirectory: modules/storage/terraform-aws-ebs 
          cdktfVersion: 0.11.2
          stackName: terraform-aws-ebs
          mode: auto-approve-apply
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
