name: "Synth the CDKTF Application on PRs"

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: "Terraform CDK Synth"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install
        with:
          working-directory: modules/storage/terraform-aws-ebs

      - name: Generate module and provider bindings
        run: npx cdktf-cli get
        with:
          working-directory: modules/storage/terraform-aws-ebs

      # Remove this step if you don't have any
      #- name: Run unit tests
      #  run: yarn test
      
      - name: Test the synth
        uses: hashicorp/terraform-cdk-action@v0.1.0
        with:
          terraformVersion: 1.3.0
          workingDirectory: modules/storage/terraform-aws-ebs 
          cdktfVersion: 0.12.2
          stackName: terraform-aws-ebs
          mode: synth-only
      
      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v0.1.0
        with:
          terraformVersion: 1.3.0
          workingDirectory: modules/storage/terraform-aws-ebs 
          cdktfVersion: 0.12.2
          stackName: terraform-aws-ebs
          mode: plan-only
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
